"""Compatibility auto-configuration for the composed neurOS SDK.

This is intentionally a user-facing composition helper, not a kernel feature:
it selects concrete drivers and models and therefore belongs in the ``neuros``
meta-distribution, which depends on those packages. New applications should
prefer versioned configuration plus plugin discovery.

The legacy :class:`neuros.pipeline.Pipeline` path applies band-power feature
extraction before decoding. It therefore supports vector decoders here, not the
maintained raw-window EEGNet/CNN/Transformer implementations. Auto-config fails
closed rather than silently substituting input semantics.
"""

from __future__ import annotations

from typing import Optional

from neuros.pipeline import Pipeline


_WINDOW_DECODERS = {"eegnet", "cnn", "transformer"}
_DEPRECATED_DECODERS = {"dino", "dino_v3"}


def _select_vector_model(desc: str, model_name: str | None) -> str:
    explicit = model_name.lower() if model_name else None
    if explicit in _WINDOW_DECODERS:
        raise ValueError(
            f"{explicit!r} is a raw-window decoder and cannot be wired through legacy "
            "generate_pipeline_for_task(), which emits band-power feature vectors. "
            "Use the config-first RuntimeGraph path or instantiate the decoder behind "
            "an explicit window-preserving transform."
        )
    if explicit in _DEPRECATED_DECODERS:
        raise ValueError(
            "The historical DinoV3Model compatibility shim is not a verified DINOv3 "
            "implementation. Use neuros-foundation with a verified upstream adapter."
        )
    if explicit:
        return explicit

    # Automatic heuristics stay within decoders whose input contract matches
    # the vector features generated by the legacy Pipeline path.
    if "ssvep" in desc or "steady state" in desc:
        return "svm"
    if "motor" in desc and "imagery" in desc:
        return "svm"
    if "regression" in desc:
        return "gbdt"
    if any(key in desc for key in ("transformer", "sequence", "convolution", "cnn")):
        raise ValueError(
            "This task description requests a raw-window neural architecture. "
            "Legacy auto-configuration cannot preserve that input contract; use a "
            "config-first RuntimeGraph instead."
        )
    return "random_forest"


def generate_pipeline_for_task(
    task_description: str,
    *,
    use_brainflow: bool = False,
    model_name: Optional[str] = None,
    fs: float = 250.0,
    channels: int = 8,
) -> Pipeline:
    if fs <= 0:
        raise ValueError("fs must be positive")
    if channels <= 0:
        raise ValueError("channels must be positive")

    try:
        from neuros.agents import BlinkAgent, CalciumAgent, FacialAgent, MotionAgent, PoseAgent, VideoAgent
        from neuros.drivers.brainflow_driver import BrainFlowDriver
        from neuros.drivers.calcium_imaging_driver import CalciumImagingDriver
        from neuros.drivers.dataset_driver import DatasetDriver
        from neuros.drivers.ecog_driver import ECoGDriver
        from neuros.drivers.emg_driver import EMGDriver
        from neuros.drivers.eog_driver import EOGDriver
        from neuros.drivers.mock_driver import MockDriver
        from neuros.drivers.motion_sensor_driver import MotionSensorDriver
        from neuros.drivers.video_driver import VideoDriver
        from neuros.models import GBDTModel, KNNModel, RandomForestModel, SVMModel, SimpleClassifier
    except ImportError as exc:
        raise RuntimeError(
            "Auto-configuration requires the neurOS driver and model packages. "
            "Install the BCI profile before calling generate_pipeline_for_task()."
        ) from exc

    desc = task_description.lower()
    name = _select_vector_model(desc, model_name)
    factories = {
        "random_forest": RandomForestModel,
        "svm": SVMModel,
        "knn": KNNModel,
        "gbdt": GBDTModel,
        "simple": SimpleClassifier,
    }
    if name not in factories:
        known = ", ".join(sorted(factories))
        raise ValueError(f"Unknown vector model name {name!r}. Supported here: {known}")
    model = factories[name]()

    bands = None
    if "ssvep" in desc:
        bands = {"alpha_beta": (8.0, 20.0)}
    elif "motor" in desc:
        bands = {"mu_beta": (8.0, 30.0)}

    processing_agent_class = None
    processing_kwargs = {}
    dataset_names = ["iris", "digits", "wine", "breast cancer", "breast_cancer", "cancer"]

    if any(key in desc for key in ["dataset", "data set", "reprocess", "reanalysis"]):
        selected = next((candidate for candidate in dataset_names if candidate in desc), "iris")
        selected_name = "breast_cancer" if selected in ("breast cancer", "cancer") else selected
        driver = DatasetDriver(dataset_name=selected_name, sampling_rate=fs)
        processing_agent_class = MotionAgent
    elif any(key in desc for key in ["calcium", "imaging", "optical", "fluorescence", "two-photon"]):
        driver = CalciumImagingDriver(frame_rate=fs)
        processing_agent_class = CalciumAgent
    elif any(key in desc for key in ["video", "pose", "facial", "blink", "face"]):
        driver = VideoDriver(frame_rate=fs, resolution=(64, 64), channels=3)
        if "pose" in desc:
            processing_agent_class = PoseAgent
        elif any(key in desc for key in ["facial", "face"]):
            processing_agent_class = FacialAgent
        elif "blink" in desc:
            processing_agent_class = BlinkAgent
        else:
            processing_agent_class = VideoAgent
    elif any(key in desc for key in ["motion", "imu", "movement", "acceleration"]):
        driver = MotionSensorDriver(sampling_rate=fs)
        processing_agent_class = MotionAgent
    elif any(key in desc for key in ["ecog", "corticography", "cortical", "intracranial"]):
        driver = ECoGDriver(sampling_rate=fs, channels=channels)
    elif any(key in desc for key in ["emg", "muscle", "myography"]):
        driver = EMGDriver(sampling_rate=fs, channels=channels)
    elif any(key in desc for key in ["eog", "ocular", "eye"]):
        driver = EOGDriver(sampling_rate=fs, channels=channels)
    else:
        driver = (
            BrainFlowDriver(board_id=0, sampling_rate=fs, channels=channels)
            if use_brainflow
            else MockDriver(sampling_rate=fs, channels=channels)
        )

    return Pipeline(
        driver=driver,
        model=model,
        fs=fs,
        bands=bands,
        adaptation=True,
        processing_agent_class=processing_agent_class,
        processing_kwargs=processing_kwargs,
    )
