"""Curated neural foundation-model landscape.

The catalog is a navigation/comparison layer, not an endorsement list. Entries
include open academic models, neurOS-native research, and commercial industry
systems when their existence/capabilities are documented by a primary source.
Closed systems remain catalog-only until a stable public API exists.
"""

from __future__ import annotations

from .schema import (
    AccessLevel,
    FoundationModelCard,
    IntegrationLevel,
    ModelStatus,
    ModelTask,
    NeuralModality,
)

M = NeuralModality
T = ModelTask
A = AccessLevel
I = IntegrationLevel
S = ModelStatus


DEFAULT_MODEL_CARDS: tuple[FoundationModelCard, ...] = (
    FoundationModelCard(
        id="neuros-neurofmx",
        name="NeuroFM-X",
        organization="neurOS",
        year=2026,
        modalities=(M.SPIKES, M.LFP, M.CALCIUM, M.MULTIMODAL),
        tasks=(T.REPRESENTATION, T.DECODING, T.FORECASTING, T.GENERATION),
        architecture="neurOS-native population-dynamics foundation model",
        pretraining_objective="multi-objective population dynamics modeling",
        input_geometry="neurOS token and population contracts",
        transfer_regimes=("pretrain", "fine_tune", "multitask", "continual"),
        access=A.OPEN_CODE,
        integration=I.NATIVE,
        status=S.RESEARCH,
        python_package="neuros_neurofm",
        license="MIT",
        code_url="https://github.com/sidhulyalkar/neurOS-v1/tree/main/packages/neuros-neurofm",
        source_url="https://github.com/sidhulyalkar/neurOS-v1/tree/main/packages/neuros-neurofm",
        notes=(
            "Native neurOS model-development package. neuros-foundation exposes interoperability instead of duplicating its architecture.",
        ),
        tags=("neurOS", "population", "native", "research"),
    ),
    FoundationModelCard(
        id="zuna-1.1",
        name="ZUNA1.1",
        organization="Zyphra",
        year=2026,
        modalities=(M.EEG,),
        tasks=(T.RECONSTRUCTION, T.DENOISING, T.IMPUTATION, T.UPSAMPLING),
        architecture="380M-parameter transformer encoder-decoder diffusion autoencoder",
        pretraining_objective="rectified-flow reconstruction under structured channel/time corruption",
        input_geometry="4D scalp-coordinate + time positional encoding; arbitrary montage",
        transfer_regimes=("zero_shot_reconstruction",),
        parameters=380_000_000,
        pretraining_scale="~3.5M EEG channel-hours (company release)",
        access=A.OPEN_WEIGHTS,
        integration=I.ADAPTER,
        status=S.RELEASED,
        python_package="zuna",
        install_extra="zuna",
        license="Apache-2.0",
        paper_url="https://www.zyphra.com/our-work/zuna1.1",
        code_url="https://github.com/Zyphra/ZUNA",
        source_url="https://www.zyphra.com/our-work/zuna1.1",
        notes=(
            "Research-use reconstruction model, not a diagnostic tool.",
            "Generated/reconstructed channels are imputed signals and can hallucinate plausible activity.",
            "Current public pipeline operates at 256 Hz and supports variable 0.5-30 s inputs.",
        ),
        tags=("eeg", "industry", "reconstruction", "montage-agnostic", "generative"),
    ),
    FoundationModelCard(
        id="emotiv-axon",
        name="Axon",
        organization="Emotiv",
        year=2026,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.DECODING),
        architecture="commercial universal EEG foundation model / Large Brain Model",
        pretraining_objective="not publicly specified",
        input_geometry="real-world multi-device EEG ecosystem",
        transfer_regimes=("commercial_platform",),
        access=A.CLOSED,
        integration=I.CATALOG,
        status=S.COMMERCIAL,
        source_url="https://www.emotiv.com/about",
        notes=(
            "Commercial system. Keep benchmark claims separate from open-model results until reproducible model access is available.",
            "Emotiv describes its ecosystem as spanning 140+ countries and 4,000+ institutions.",
        ),
        tags=("eeg", "industry", "commercial", "real-world-data"),
    ),
    FoundationModelCard(
        id="eeg-x",
        name="EEG-X",
        organization="Emotiv / Monash University",
        year=2025,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.RECONSTRUCTION, T.DENOISING, T.CLASSIFICATION),
        architecture="device-agnostic EEG encoder with location-based channel embeddings and DiCT transform",
        pretraining_objective="noise-aware raw/latent reconstruction toward denoised targets",
        input_geometry="location-based channel embedding; variable channels and recording lengths",
        transfer_regimes=("linear_probe", "fine_tune", "cross_device"),
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RESEARCH,
        code_url="https://github.com/Emotiv/EEG-X",
        paper_url="https://arxiv.org/abs/2511.08861",
        source_url="https://www.emotiv.com/our-technology",
        tags=("eeg", "device-agnostic", "noise-robust", "industry-research"),
    ),
    FoundationModelCard(
        id="manas-1",
        name="MANAS-1",
        organization="NeuroDX",
        year=2026,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.CLASSIFICATION, T.DECODING),
        architecture="600M-parameter MAE-based Brain Language Foundation Model (company description)",
        pretraining_objective="masked autoencoding",
        input_geometry="4D spatial/temporal/spectral/channel encoding with PatchConv frontend",
        transfer_regimes=("cross_subject", "fine_tune"),
        parameters=600_000_000,
        access=A.CLOSED,
        integration=I.CATALOG,
        status=S.COMMERCIAL,
        source_url="https://www.neurodx.ai/",
        notes=(
            "Commercial/company-reported metrics should not be mixed with independently reproduced benchmark results.",
        ),
        tags=("eeg", "industry", "clinical-research", "masked-autoencoder"),
    ),
    FoundationModelCard(
        id="reve-base",
        name="REVE",
        organization="BRAIN / IMT Atlantique collaborators",
        year=2025,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.CLASSIFICATION, T.DECODING),
        architecture="transformer EEG encoder with 4D positional encoding",
        pretraining_objective="masked autoencoding",
        input_geometry="arbitrary electrode arrangements and signal lengths",
        transfer_regimes=("linear_probe", "fine_tune", "low_shot"),
        parameters=72_000_000,
        pretraining_scale=">60,000 EEG hours; 92 datasets; ~25,000 subjects",
        access=A.OPEN_WEIGHTS,
        integration=I.CATALOG,
        status=S.RELEASED,
        python_package="transformers",
        license="MIT code; verify model-weight terms separately",
        paper_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/20a917f77773ac0fa8bea2bdd6606b66-Abstract-Conference.html",
        code_url="https://github.com/elouayas/reve_eeg",
        weights_url="https://huggingface.co/brain-bzh/reve-base",
        source_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/20a917f77773ac0fa8bea2bdd6606b66-Abstract-Conference.html",
        tags=("eeg", "open", "4d-position", "masked-autoencoder"),
    ),
    FoundationModelCard(
        id="neuript",
        name="NeurIPT",
        organization="National University of Singapore collaborators",
        year=2025,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.CLASSIFICATION, T.DECODING),
        architecture="progressive Mixture-of-Experts transformer",
        pretraining_objective="Amplitude-Aware Masked Pretraining (AAMP)",
        input_geometry="3D electrode coordinates with downstream intra/inter-lobe pooling",
        transfer_regimes=("fine_tune", "cross_setup"),
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RESEARCH,
        paper_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/dd9c5ce8803e1898d438e636fbae0236-Abstract-Conference.html",
        source_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/dd9c5ce8803e1898d438e636fbae0236-Abstract-Conference.html",
        tags=("eeg", "moe", "electrode-coordinates", "bci"),
    ),
    FoundationModelCard(
        id="luna-eeg",
        name="LUNA",
        organization="ETH Zurich / University of Zurich collaborators",
        year=2025,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.CLASSIFICATION, T.RECONSTRUCTION),
        architecture="topology-agnostic latent-query encoder with temporal transformer",
        pretraining_objective="masked-patch reconstruction",
        input_geometry="learned latent queries decouple compute from channel count",
        transfer_regimes=("fine_tune", "cross_montage"),
        pretraining_scale=">21,000 raw EEG hours on TUEG + Siena",
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RELEASED,
        paper_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/66969a9e6bd7a26dfeccea7227178ca7-Abstract-Conference.html",
        code_url="https://github.com/pulp-bio/biofoundation",
        source_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/66969a9e6bd7a26dfeccea7227178ca7-Abstract-Conference.html",
        tags=("eeg", "efficient", "topology-agnostic", "open"),
    ),
    FoundationModelCard(
        id="csbrain",
        name="CSBrain",
        organization="Shanghai AI Laboratory collaborators",
        year=2025,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.CLASSIFICATION, T.DECODING),
        architecture="cross-scale spatiotemporal EEG foundation model",
        pretraining_objective="multi-scale self-supervision",
        input_geometry="cross-scale spatial and temporal structure",
        transfer_regimes=("fine_tune",),
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RESEARCH,
        paper_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/7e199ad8ae40eb19b2980f61f659cb07-Abstract-Conference.html",
        source_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/7e199ad8ae40eb19b2980f61f659cb07-Abstract-Conference.html",
        tags=("eeg", "cross-scale", "spatiotemporal"),
    ),
    FoundationModelCard(
        id="eegpt",
        name="EEGPT",
        organization="Shanghai Jiao Tong University collaborators",
        year=2024,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.CLASSIFICATION, T.DECODING),
        architecture="~10M-parameter spatiotemporal transformer",
        pretraining_objective="masked dual self-supervision with spatiotemporal alignment",
        input_geometry="channel-aware EEG patches",
        transfer_regimes=("linear_probe", "fine_tune"),
        parameters=10_000_000,
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RELEASED,
        source_url="https://proceedings.neurips.cc/",
        tags=("eeg", "compact", "masked-modeling"),
    ),
    FoundationModelCard(
        id="labram",
        name="LaBraM",
        organization="Shanghai Jiao Tong University collaborators",
        year=2024,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.CLASSIFICATION, T.DECODING),
        architecture="Large Brain Model with neural tokenizer and transformer encoder",
        pretraining_objective="masked neural token prediction",
        input_geometry="channel/time neural tokens",
        transfer_regimes=("linear_probe", "fine_tune"),
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RELEASED,
        source_url="https://openreview.net/",
        tags=("eeg", "tokenizer", "iclr-2024"),
    ),
    FoundationModelCard(
        id="cbramod",
        name="CBraMod",
        organization="EEG foundation-model research community",
        year=2025,
        modalities=(M.EEG,),
        tasks=(T.REPRESENTATION, T.CLASSIFICATION, T.DECODING),
        architecture="criss-cross brain foundation model",
        pretraining_objective="masked EEG representation learning",
        input_geometry="spatiotemporal EEG patches",
        transfer_regimes=("linear_probe", "fine_tune"),
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RELEASED,
        source_url="https://openreview.net/",
        tags=("eeg", "iclr-2025", "representation"),
    ),
    FoundationModelCard(
        id="neurolm",
        name="NeuroLM",
        organization="Shanghai Jiao Tong University / Microsoft Research collaborators",
        year=2025,
        modalities=(M.EEG, M.TEXT, M.MULTIMODAL),
        tasks=(T.REPRESENTATION, T.DECODING, T.BRAIN_LANGUAGE, T.MULTIMODAL_ALIGNMENT),
        architecture="EEG tokenizer + language-model bridge for multi-task neural decoding",
        pretraining_objective="neural token modeling and EEG-language alignment",
        input_geometry="EEG tokens aligned with language-token space",
        transfer_regimes=("prompted", "fine_tune", "multitask"),
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RELEASED,
        source_url="https://openreview.net/",
        tags=("eeg", "language", "multimodal", "iclr-2025"),
    ),
    FoundationModelCard(
        id="ndt3",
        name="NDT3 / Generalist Intracortical Motor Decoder",
        organization="University of Pittsburgh / Carnegie Mellon collaborators",
        year=2025,
        modalities=(M.SPIKES, M.BEHAVIOR),
        tasks=(T.DECODING, T.REPRESENTATION, T.REGRESSION, T.FORECASTING),
        architecture="autoregressive transformer for neural population activity + motor covariates",
        pretraining_objective="autoregressive neural/covariate modeling",
        input_geometry="population spike tokens with session/context structure",
        transfer_regimes=("pretrain_then_fine_tune", "cross_session", "cross_subject"),
        pretraining_scale="~2,000 hours; >30 monkeys and humans",
        access=A.OPEN_WEIGHTS,
        integration=I.CATALOG,
        status=S.RELEASED,
        paper_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/a00000e6a2208172700510bcd69d48e9-Abstract-Conference.html",
        source_url="https://proceedings.neurips.cc/paper_files/paper/2025/hash/a00000e6a2208172700510bcd69d48e9-Abstract-Conference.html",
        tags=("intracortical", "spikes", "motor", "bci"),
    ),
    FoundationModelCard(
        id="poyo-plus",
        name="POYO+",
        organization="Meta / academic collaborators",
        year=2025,
        modalities=(M.SPIKES, M.BEHAVIOR),
        tasks=(T.DECODING, T.REPRESENTATION, T.REGRESSION, T.CLASSIFICATION),
        architecture="Perceiver-style neural population decoder with unit/session/task tokens",
        pretraining_objective="multi-session, multi-task supervised neural decoding",
        input_geometry="spike-event tokens with learned unit/session identity",
        transfer_regimes=("multisession", "multitask", "fine_tune"),
        access=A.OPEN_CODE,
        integration=I.LEGACY,
        status=S.RELEASED,
        source_url="https://github.com/neuro-galaxy/torch_brain",
        notes=(
            "The historical neurOS POYOModel wrapper is retained for compatibility but is not benchmark-grade until it delegates to the upstream implementation end-to-end.",
        ),
        tags=("spikes", "population", "multisession", "legacy-wrapper"),
    ),
    FoundationModelCard(
        id="brant",
        name="Brant",
        organization="Zhejiang University collaborators",
        year=2023,
        modalities=(M.ECOG, M.SEEG),
        tasks=(T.REPRESENTATION, T.FORECASTING, T.IMPUTATION, T.CLASSIFICATION),
        architecture="large intracranial signal transformer with time/frequency modeling",
        pretraining_objective="intracranial signal forecasting / representation pretraining",
        input_geometry="multichannel intracranial time-frequency signals",
        transfer_regimes=("fine_tune", "low_resource"),
        access=A.GATED,
        integration=I.CATALOG,
        status=S.RELEASED,
        paper_url="https://proceedings.neurips.cc/paper_files/paper/2023/hash/535915d26859036410b0533804cee788-Abstract-Conference.html",
        source_url="https://proceedings.neurips.cc/paper_files/paper/2023/hash/535915d26859036410b0533804cee788-Abstract-Conference.html",
        tags=("intracranial", "seeg", "ecog", "forecasting"),
    ),
    FoundationModelCard(
        id="brainlm",
        name="BrainLM",
        organization="Yale / Meta collaborators",
        year=2024,
        modalities=(M.FMRI,),
        tasks=(T.REPRESENTATION, T.FORECASTING, T.CLASSIFICATION),
        architecture="transformer foundation model for fMRI activity sequences",
        pretraining_objective="masked brain-activity prediction",
        input_geometry="parcellated whole-brain fMRI time series",
        transfer_regimes=("zero_shot", "fine_tune"),
        pretraining_scale="~6,700 hours of fMRI",
        access=A.OPEN_CODE,
        integration=I.CATALOG,
        status=S.RELEASED,
        source_url="https://openreview.net/",
        tags=("fmri", "whole-brain", "masked-modeling"),
    ),
    FoundationModelCard(
        id="cebra",
        name="CEBRA",
        organization="EPFL / Adaptive Motor Control Lab collaborators",
        year=2023,
        modalities=(M.SPIKES, M.CALCIUM, M.BEHAVIOR),
        tasks=(T.REPRESENTATION, T.DECODING),
        architecture="contrastive neural representation learner",
        pretraining_objective="time- and behavior-contrastive learning",
        input_geometry="continuous neural population vectors",
        transfer_regimes=("fit", "cross_session_alignment"),
        access=A.OPEN_CODE,
        integration=I.LEGACY,
        status=S.RELEASED,
        python_package="cebra",
        install_extra="cebra",
        code_url="https://github.com/AdaptiveMotorControlLab/CEBRA",
        source_url="https://www.nature.com/articles/s41586-023-06031-6",
        notes=(
            "CEBRA is an important representation-learning baseline, but not every CEBRA configuration is a pretrained foundation model.",
            "The existing neurOS CEBRAModel wrapper is legacy and should not be used to claim upstream CEBRA results until it executes the upstream library.",
        ),
        tags=("contrastive", "spikes", "calcium", "representation", "legacy-wrapper"),
    ),
    FoundationModelCard(
        id="neuroformer",
        name="Neuroformer",
        organization="Neuroformer authors",
        year=2024,
        modalities=(M.SPIKES, M.BEHAVIOR, M.VIDEO, M.MULTIMODAL),
        tasks=(T.FORECASTING, T.GENERATION, T.DECODING, T.REPRESENTATION),
        architecture="multimodal autoregressive transformer for neural activity and behavior",
        pretraining_objective="generative next-token / multimodal forecasting",
        input_geometry="tokenized spikes plus behavioral/stimulus context",
        transfer_regimes=("generative_pretraining", "fine_tune"),
        access=A.OPEN_CODE,
        integration=I.LEGACY,
        status=S.RESEARCH,
        code_url="https://github.com/nerdslab/neuroformer",
        notes=(
            "The historical neurOS NeuroformerModel is a local placeholder, not an upstream Neuroformer execution backend.",
        ),
        tags=("spikes", "multimodal", "generative", "legacy-wrapper"),
    ),
    FoundationModelCard(
        id="mvpformer",
        name="MVPFormer",
        organization="NeurIPS 2025 Brain and Body workshop collaborators",
        year=2025,
        modalities=(M.ECOG, M.SEEG),
        tasks=(T.GENERATION, T.FORECASTING, T.CLASSIFICATION, T.DECODING),
        architecture="multivariate parallel-attention generative transformer",
        pretraining_objective="generative neuronal activity forecasting",
        input_geometry="heterogeneous intracranial channel configurations",
        transfer_regimes=("cross_subject", "fine_tune"),
        pretraining_scale="paired with a released long-term iEEG corpus approaching 10,000 hours",
        access=A.OPEN_WEIGHTS,
        integration=I.CATALOG,
        status=S.RESEARCH,
        source_url="https://neurips.cc/virtual/2025/132669",
        tags=("ieeg", "generative", "variable-channels", "open"),
    ),
)


def catalog_by_id() -> dict[str, FoundationModelCard]:
    return {card.id: card for card in DEFAULT_MODEL_CARDS}
