name: neurofm_v2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10

  # PyTorch with CUDA support (for RTX 3070 Ti)
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8

  # Core scientific computing
  - numpy=1.26.4          # Pinned version
  - scipy>=1.10.0
  - pandas>=1.5.0
  - hdmf                    # Explicitly added

  # Mamba-SSM Dependencies
  - packaging
  - ninja
    
  # Data handling
  - h5py>=3.8.0
  - pynwb>=2.5.0

  # Utilities
  - tqdm
  - requests

  # Install remaining with pip
  - pip
  - pip:
      - xarray
      - nest-asyncio
      - cachetools
      - boto3
      - simplejson
      - psycopg2-binary
      - mamba-ssm