[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neuros-models"
version = "2.0.0"
description = "Deep learning models for neurOS - EEGNet, Transformers, LSTM, and more"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "neurOS Development Team"}
]
keywords = ["neuroscience", "deep-learning", "eegnet", "transformer", "neural-decoding"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = [
    "neuros-core>=2.0.0",
    "numpy>=1.24.0",
    "scikit-learn>=1.2",
]

[project.optional-dependencies]
pytorch = [
    "torch>=2.1.0",
]
sklearn = [
    "scikit-learn>=1.2",
]
all = [
    "torch>=2.1.0",
    "scikit-learn>=1.2",
]

[project.urls]
Homepage = "https://github.com/<your-user>/neuros2"
Documentation = "https://neuros.readthedocs.io"
Repository = "https://github.com/<your-user>/neuros2"
Issues = "https://github.com/<your-user>/neuros2/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["neuros*"]
namespaces = true

[tool.setuptools.package-data]
neuros = ["py.typed"]
