apiVersion: v1
kind: Namespace
metadata:
  name: ray-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberay-operator
  namespace: ray-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberay-operator
rules:
- apiGroups: ["ray.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "events", "configmaps", "secrets", "persistentvolumeclaims", "serviceaccounts"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses", "ingresses"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberay-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberay-operator
subjects:
- kind: ServiceAccount
  name: kuberay-operator
  namespace: ray-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
  namespace: ray-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kuberay-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kuberay-operator
    spec:
      serviceAccountName: kuberay-operator
      containers:
      - name: manager
        image: quay.io/kuberay/operator:v1.1.1
        imagePullPolicy: IfNotPresent
        command: ["/manager"]
        args:
        - --leader-elect
        env:
        - name: WATCH_NAMESPACE
          value: ""
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
