[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neuros-cloud"
version = "2.0.0"
description = "Cloud infrastructure for neurOS - Kafka, AWS SageMaker, WebDataset, Zarr export"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "neurOS Development Team"}
]
keywords = ["neuroscience", "cloud", "kafka", "sagemaker", "distributed", "webdataset"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Distributed Computing",
]

dependencies = [
    "neuros-core>=2.0.0",
]

[project.optional-dependencies]
kafka = [
    "confluent-kafka>=2.1.1",
    "pyzmq>=25.0.2",
    "redis>=4.6.0",
]
aws = [
    "boto3>=1.26.0",
    "sagemaker>=2.200.0",
]
export = [
    "webdataset>=0.2.48",
    "ome-zarr>=0.8.1",
    "pyarrow>=15.0.0",
]
monitoring = [
    "prometheus-client>=0.17.1",
    "mlflow>=2.11.1",
    "wandb>=0.16.0",
]
all = [
    "confluent-kafka>=2.1.1",
    "pyzmq>=25.0.2",
    "redis>=4.6.0",
    "boto3>=1.26.0",
    "sagemaker>=2.200.0",
    "webdataset>=0.2.48",
    "ome-zarr>=0.8.1",
    "pyarrow>=15.0.0",
    "prometheus-client>=0.17.1",
    "mlflow>=2.11.1",
    "wandb>=0.16.0",
]

[project.urls]
Homepage = "https://github.com/<your-user>/neuros2"
Documentation = "https://neuros.readthedocs.io"
Repository = "https://github.com/<your-user>/neuros2"
Issues = "https://github.com/<your-user>/neuros2/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["neuros*"]
namespaces = true

[tool.setuptools.package-data]
neuros = ["py.typed"]
