[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neuros"
version = "2.0.0"
description = "A modular operating system for brain-computer interfaces (meta-package)"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "neurOS Development Team"}
]
keywords = ["neuroscience", "bci", "brain-computer-interface", "eeg", "neural-decoding"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

# Standard installation: core + drivers + models
dependencies = [
    "neuros-core>=2.0.0",
    "neuros-drivers>=2.0.0",
    "neuros-models>=2.0.0",
]

[project.optional-dependencies]
# Full installation (everything)
all = [
    "neuros-foundation>=2.0.0",
    "neuros-ui>=2.0.0",
    "neuros-cloud>=2.0.0",
]

# BCI applications
bci = [
    "neuros-drivers[eeg]>=2.0.0",
    "neuros-models[pytorch]>=2.0.0",
    "neuros-ui[dashboard]>=2.0.0",
]

# Research with foundation models
research = [
    "neuros-models[all]>=2.0.0",
    "neuros-foundation[all]>=2.0.0",
]

# Production deployment
deployment = [
    "neuros-ui[all]>=2.0.0",
    "neuros-cloud[all]>=2.0.0",
]

# Development and testing
dev = [
    "pytest>=7.2",
    "pytest-cov>=4.0",
    "pytest-asyncio>=0.21",
    "black>=23.0",
    "ruff>=0.1.0",
]

[project.scripts]
neuros = "neuros.cli:main"

[project.urls]
Homepage = "https://github.com/<your-user>/neuros2"
Documentation = "https://neuros.readthedocs.io"
Repository = "https://github.com/<your-user>/neuros2"
Issues = "https://github.com/<your-user>/neuros2/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["neuros*"]
namespaces = true

[tool.setuptools.package-data]
neuros = ["py.typed"]
