"""Storage integrations for the experimental :mod:`neuros.cloud` package.

The public contract is intentionally small. ``LocalStorage`` provides a local
filesystem proving path. ``S3Storage`` is exposed only when boto3 is installed.
Encryption is opt-in through ``NEUROS_ENCRYPTION_KEY`` and fails closed: the
value must be a valid Fernet key and the ``security`` extra must be installed.
No custom cipher or plaintext sidecar is used when encryption is requested.
"""

from __future__ import annotations

import base64
import io
import json
import os
import shutil
import threading
from abc import ABC, abstractmethod
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

__all__ = ["CloudStorage", "LocalStorage"]

try:
    import boto3  # type: ignore
    from botocore.exceptions import ClientError, NoCredentialsError  # type: ignore

    HAS_BOTO3 = True
except ImportError:  # pragma: no cover - optional provider dependency
    HAS_BOTO3 = False


StreamResult = tuple[float, int, float, float]


def _run_id(value: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError("run_id must be a nonblank string")
    if value in {".", ".."} or "/" in value or "\\" in value or "\x00" in value:
        raise ValueError("run_id must be a single path-safe identifier")
    return value


def _encryption_key() -> bytes | None:
    raw = os.getenv("NEUROS_ENCRYPTION_KEY")
    if raw is None or not raw.strip():
        return None
    try:
        key = raw.encode("ascii")
    except UnicodeEncodeError as exc:
        raise ValueError("NEUROS_ENCRYPTION_KEY must be an ASCII Fernet key") from exc
    try:
        decoded = base64.urlsafe_b64decode(key)
    except Exception as exc:
        raise ValueError("NEUROS_ENCRYPTION_KEY must be a valid Fernet key") from exc
    if len(decoded) != 32:
        raise ValueError("NEUROS_ENCRYPTION_KEY must decode to exactly 32 bytes")
    return key


def _fernet():
    key = _encryption_key()
    if key is None:
        return None
    try:
        from cryptography.fernet import Fernet  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "Encrypted local storage requires the neuros-cloud[security] extra"
        ) from exc
    try:
        return Fernet(key)
    except Exception as exc:
        raise ValueError("NEUROS_ENCRYPTION_KEY is not a valid Fernet key") from exc


def _atomic_write_text(path: Path, text: str) -> None:
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}-{threading.get_ident()}")
    try:
        temporary.write_text(text, encoding="utf-8")
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


class CloudStorage(ABC):
    """Abstract storage backend used by optional neurOS integrations."""

    @abstractmethod
    def upload_metrics(self, metrics: Mapping[str, float], run_id: str) -> None:
        """Persist one run's scalar metrics."""
        raise NotImplementedError

    @abstractmethod
    def stream_results(self, results: Iterable[StreamResult], run_id: str) -> None:
        """Persist timestamp, label, confidence, and latency tuples."""
        raise NotImplementedError

    def upload_database(self, db_path: str | os.PathLike[str]) -> None:
        """Optionally persist a database artifact."""
        return


class LocalStorage(CloudStorage):
    """Filesystem storage with an explicit plaintext-or-Fernet boundary.

    With no ``NEUROS_ENCRYPTION_KEY`` the historical plaintext JSON/log and
    base64-encoded compatibility files are written. Base64 is encoding only,
    never a confidentiality mechanism.

    When ``NEUROS_ENCRYPTION_KEY`` is present, it must be a standard Fernet
    key generated by ``Fernet.generate_key()``. Only encrypted ``*.enc`` files
    are written for metrics and stream records. Existing plaintext sidecars for
    the same run are removed after the encrypted write succeeds.
    """

    def __init__(self, base_dir: str | os.PathLike[str] = "~/neuros_runs") -> None:
        self.base_path = Path(os.path.expanduser(os.fspath(base_dir))).resolve()
        self.base_path.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()

    def _run_dir(self, run_id: str) -> Path:
        safe_id = _run_id(run_id)
        directory = (self.base_path / safe_id).resolve()
        if directory.parent != self.base_path:
            raise ValueError("run_id resolves outside the configured storage directory")
        directory.mkdir(parents=True, exist_ok=True)
        return directory

    def upload_metrics(self, metrics: Mapping[str, float], run_id: str) -> None:
        payload = json.dumps(dict(metrics), indent=2, sort_keys=True, allow_nan=False)
        encryptor = _fernet()
        with self._lock:
            run_dir = self._run_dir(run_id)
            plain_path = run_dir / "metrics.json"
            b64_path = run_dir / "metrics.b64"
            encrypted_path = run_dir / "metrics.enc"

            if encryptor is None:
                _atomic_write_text(plain_path, payload)
                encoded = base64.b64encode(payload.encode("utf-8")).decode("ascii")
                _atomic_write_text(b64_path, encoded)
                encrypted_path.unlink(missing_ok=True)
                return

            token = encryptor.encrypt(payload.encode("utf-8")).decode("ascii")
            _atomic_write_text(encrypted_path, token)
            plain_path.unlink(missing_ok=True)
            b64_path.unlink(missing_ok=True)

    def stream_results(self, results: Iterable[StreamResult], run_id: str) -> None:
        encryptor = _fernet()
        with self._lock:
            run_dir = self._run_dir(run_id)
            log_path = run_dir / "stream.log"
            b64_path = run_dir / "stream.b64"
            encrypted_path = run_dir / "stream.enc"

            if encryptor is None:
                encrypted_path.unlink(missing_ok=True)
                with log_path.open("a", encoding="utf-8") as plain, b64_path.open(
                    "a", encoding="utf-8"
                ) as encoded:
                    for timestamp, label, confidence, latency in results:
                        line = (
                            f"{timestamp:.3f}\t{label}\t{confidence:.3f}"
                            f"\t{latency:.6f}\n"
                        )
                        plain.write(line)
                        encoded.write(
                            base64.b64encode(line.encode("utf-8")).decode("ascii") + "\n"
                        )
                return

            tokens: list[str] = []
            for timestamp, label, confidence, latency in results:
                line = (
                    f"{timestamp:.3f}\t{label}\t{confidence:.3f}"
                    f"\t{latency:.6f}\n"
                )
                tokens.append(encryptor.encrypt(line.encode("utf-8")).decode("ascii"))
            if tokens:
                with encrypted_path.open("a", encoding="utf-8") as encrypted:
                    for token in tokens:
                        encrypted.write(token + "\n")
            log_path.unlink(missing_ok=True)
            b64_path.unlink(missing_ok=True)

    def upload_database(self, db_path: str | os.PathLike[str]) -> None:
        source = Path(db_path)
        if not source.is_file():
            raise FileNotFoundError(source)
        destination = self.base_path / source.name
        with self._lock:
            shutil.copy2(source, destination)


if HAS_BOTO3:

    class S3Storage(CloudStorage):  # pragma: no cover - provider integration
        """Thin Amazon S3 storage adapter.

        Provider credentials, bucket policy, encryption-at-rest, network policy,
        and deployment qualification remain external operational authority.
        """

        def __init__(self, bucket: str, *, prefix: str = "", s3_client: Any = None) -> None:
            if not isinstance(bucket, str) or not bucket.strip():
                raise ValueError("bucket must be a nonblank string")
            self.bucket = bucket
            self.prefix = prefix.strip("/")
            self.s3 = s3_client or boto3.client("s3")

        def _object_key(self, run_id: str, filename: str) -> str:
            parts = [part for part in (self.prefix, run_id.strip("/"), filename) if part]
            return "/".join(parts)

        def upload_metrics(self, metrics: Mapping[str, float], run_id: str) -> None:
            data = json.dumps(dict(metrics), sort_keys=True, allow_nan=False).encode("utf-8")
            key = self._object_key(run_id, "metrics.json")
            try:
                self.s3.put_object(
                    Bucket=self.bucket,
                    Key=key,
                    Body=data,
                    ContentType="application/json",
                )
            except (NoCredentialsError, ClientError) as exc:
                raise RuntimeError(f"Failed to upload metrics to S3: {exc}") from exc

        def stream_results(self, results: Iterable[StreamResult], run_id: str) -> None:
            buffer = io.StringIO()
            for timestamp, label, confidence, latency in results:
                buffer.write(
                    f"{timestamp:.3f}\t{label}\t{confidence:.3f}\t{latency:.6f}\n"
                )
            key = self._object_key(run_id, "stream.log")
            try:
                self.s3.put_object(
                    Bucket=self.bucket,
                    Key=key,
                    Body=buffer.getvalue().encode("utf-8"),
                    ContentType="text/plain",
                )
            except (NoCredentialsError, ClientError) as exc:
                raise RuntimeError(f"Failed to upload stream results to S3: {exc}") from exc

        def upload_database(self, db_path: str | os.PathLike[str]) -> None:
            source = Path(db_path)
            if not source.is_file():
                raise FileNotFoundError(source)
            key = self._object_key("", source.name)
            try:
                with source.open("rb") as database:
                    self.s3.put_object(
                        Bucket=self.bucket,
                        Key=key,
                        Body=database,
                        ContentType="application/x-sqlite3",
                    )
            except (NoCredentialsError, ClientError) as exc:
                raise RuntimeError(f"Failed to upload database to S3: {exc}") from exc

    __all__.append("S3Storage")
