[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neuros-sourceweigher"
version = "0.1.0"
description = "Microservice for estimating source mixture weights in neurOS"
authors = [ { name = "neurOS Contributors" } ]
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "fastapi>=0.100.0",
    "pydantic>=1.10.0",
    "numpy>=1.20.0"
]

[project.optional-dependencies]
dev = ["uvicorn[standard]", "pytest"]

[tool.setuptools.packages.find]
where = ["src"]